version: "3.9"

services:

  backend:
    build: ./backend
    container_name: insta_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongodb:27017/instagram
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend
    container_name: insta_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: insta_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: insta_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: insta_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data: